### Teste para listar chamados
GET http://localhost:3000/chamados
Content-Type: application/json




### Teste para criar chamados
POST http://localhost:3000/chamados
Content-Type: application/json

{
 "id": "2",
 "solicitante":"Maria",
 "problema": "Sem sinal de rede",
 "prioridade": "baixa",
 "status": "aberto"
}





### Teste chamado pelo ID
GET http://localhost:3000/chamados/1
Content-Type: = application/json

 {


 }


###

###Test para editar Chamados
PUT http://localhost:3000/chamados/2
Content-type: application/json

{
  
"id": "2",
"prioridade": "alta",
"status": "abert0"


}


###Teste para deletar chamado
DELETE http://localhost:3000/chamados
Content-Type: application/json
{
  "id": "2"

}
###